# Generated by extract-cbb.cjs; run only in an authorized Vivado environment.
set script_dir [file dirname [info script]]
if {[info exists ::env(CBB_EDA_SCRIPT_DIR)] && $::env(CBB_EDA_SCRIPT_DIR) ne ""} { set script_dir $::env(CBB_EDA_SCRIPT_DIR) }
proc cbb_eda_path {relative} { global script_dir; return [file join $script_dir $relative] }
set part [lindex $argv 0]
if {$part eq ""} { error "part argument is required" }
create_project -in_memory pulse_merge
set_property part $part [current_project]
read_verilog -sv [cbb_eda_path {../rtl/pulse_merge.sv}]
read_xdc [cbb_eda_path {../constraints/pulse_merge.xdc}]
synth_design -top pulse_merge -part $part
set synth_meta [open synth-meta.json w]
puts $synth_meta [format {{"asset_uid":"pulse_merge","top":"pulse_merge","part":"%s","stage":"synth_design"}} $part]
close $synth_meta
report_utilization -file utilization.rpt
report_timing_summary -file timing-summary.rpt
report_clocks -file clocks.rpt
write_checkpoint -force post_synth.dcp
close_project
