#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { detect: detectEda, pickLintTool } = require('./eda-detect.cjs');
const { HARNESS_ROOT } = require('./lib/harness-root.cjs');
const {
  ensureProjectDirs,
  modulePaths,
  writeDirectoryContract,
} = require('./lib/project-directory-contract.cjs');

function usage() {
  return [
    'Usage:',
    '  node engine/scripts/harness-init.cjs --project <name> [--device <part>] [--fmax <MHz>] [--dir <path>]',
    '',
    'Creates the canonical HDL project layout:',
    '  01_src/00_hdl/<module>/<module>.sv',
    '  02_sim/<module>/tb_<module>.sv',
    '  03_xdc/',
    '  06_doc/',
    '  var/project-init/directory-contract.json',
  ].join('\n');
}

function argValue(args, name, fallback = '') {
  const idx = args.indexOf(name);
  return idx >= 0 && args[idx + 1] ? args[idx + 1] : fallback;
}

function ask(prompt, defaultVal = '') {
  return new Promise((resolve) => {
    const rl = require('node:readline').createInterface({ input: process.stdin, output: process.stdout });
    const hint = defaultVal ? ` [${defaultVal}]` : '';
    rl.question(`${prompt}${hint}: `, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultVal);
    });
  });
}

function ok(message) {
  console.log(`  OK ${message}`);
}

function section(title) {
  console.log(`\n=== ${title} ===`);
}

function detectTools() {
  try {
    return detectEda();
  } catch (error) {
    return {
      tools: [],
      recommendations: [`EDA detection failed: ${error.message}`],
    };
  }
}

function toolchainLabel(tools) {
  if (tools.find((tool) => tool.name === 'xvlog' && tool.available)) return 'Vivado';
  if (tools.find((tool) => tool.name === 'vlog' && tool.available)) return 'Questa/ModelSim';
  if (tools.find((tool) => tool.name === 'iverilog' && tool.available)) return 'Icarus';
  if (tools.find((tool) => tool.name === 'verilator' && tool.available)) return 'Verilator';
  return 'manual';
}

function generateMakefile(projectName, lintTool, simulator, edaTools) {
  const harnessRoot = HARNESS_ROOT.replace(/\\/g, '/');
  let includeLine = '# No supported EDA toolchain was detected; configure VLOG/VSIM manually.';
  if (edaTools.find((tool) => tool.name === 'xvlog' && tool.available)) {
    includeLine = `HARNESS_DIR ?= ${harnessRoot}\ninclude $(HARNESS_DIR)/engine/toolchains/vivado.mk`;
  } else if (edaTools.find((tool) => tool.name === 'vlog' && tool.available)) {
    includeLine = `HARNESS_DIR ?= ${harnessRoot}\ninclude $(HARNESS_DIR)/engine/toolchains/questa.mk`;
  } else if (edaTools.find((tool) => tool.name === 'iverilog' && tool.available)) {
    includeLine = `HARNESS_DIR ?= ${harnessRoot}\ninclude $(HARNESS_DIR)/engine/toolchains/iverilog.mk`;
  }

  return `# ${projectName} - generated by harness-init
# Toolchain: ${lintTool?.label || toolchainLabel(edaTools)}
# Simulator: ${simulator || 'manual'}

.PHONY: all lint compile sim clean regress help

${includeLine}

TOP_MODULE ?= ${projectName}_top
HDL_DIR    ?= 01_src/00_hdl
SIM_DIR    ?= 02_sim

all: lint compile

lint:
\t@echo "lint $(HDL_DIR)"

compile:
\t@echo "compile $(HDL_DIR) $(SIM_DIR)"

sim:
\t@echo "sim $(TOP_MODULE)"

regress: lint compile sim
\t@echo "regression complete"

clean:
\trm -rf work transcript *.log *.jou *.vcd *.vcd.lxt *.wlf *.vvp xsim.dir .Xil __pycache__

help:
\t@echo "Targets: lint compile sim regress clean"
`;
}

function generateConstraints(fmax, device) {
  const mhz = Number.parseInt(String(fmax || '200'), 10) || 200;
  const period = (1000 / mhz).toFixed(3);
  return `# FPGA constraints budget
target:
  device: ${device || 'xc7k325tffg900-2'}
  fmax_mhz: ${mhz}

clocks:
  - name: i_clk
    period_ns: ${period}
    ports: [i_clk]
`;
}

function generateModule(name) {
  return `module ${name} #(
  parameter int P_DATA_WIDTH = 16
) (
  input  logic                    i_clk,
  input  logic                    i_rst,
  input  logic                    ri_in_valid,
  input  logic [P_DATA_WIDTH-1:0] ri_in_data,
  output logic                    ro_in_ready,
  output logic                    ro_out_valid,
  output logic [P_DATA_WIDTH-1:0] ro_out_data,
  input  logic                    ri_out_ready
);

  logic [P_DATA_WIDTH-1:0] ri_data;
  logic                   r_valid;

  always_ff @(posedge i_clk) begin
    if (i_rst) begin
      ri_data      <= '0;
      r_valid      <= 1'b0;
      ro_in_ready  <= 1'b1;
      ro_out_valid <= 1'b0;
      ro_out_data  <= '0;
    end else begin
      ro_in_ready  <= !r_valid || ri_out_ready;
      ro_out_valid <= r_valid;
      if (ri_in_valid && ro_in_ready) begin
        ri_data     <= ri_in_data;
        ro_out_data <= ri_in_data;
        r_valid     <= 1'b1;
      end else if (ri_out_ready) begin
        r_valid <= 1'b0;
      end
    end
  end

endmodule
`;
}

function generateTb(name) {
  return '`timescale 1ns/1ps\n'
    + `module tb_${name};
  logic i_clk;
  logic i_rst;
  logic ri_in_valid;
  logic [15:0] ri_in_data;
  logic ro_in_ready;
  logic ro_out_valid;
  logic [15:0] ro_out_data;
  logic ri_out_ready;

  ${name} u_dut (
    .i_clk(i_clk),
    .i_rst(i_rst),
    .ri_in_valid(ri_in_valid),
    .ri_in_data(ri_in_data),
    .ro_in_ready(ro_in_ready),
    .ro_out_valid(ro_out_valid),
    .ro_out_data(ro_out_data),
    .ri_out_ready(ri_out_ready)
  );

  initial i_clk = 1'b0;
  always #5 i_clk = ~i_clk;

  initial begin
    i_rst = 1'b1;
    ri_in_valid = 1'b0;
    ri_in_data = '0;
    ri_out_ready = 1'b1;
    repeat (4) @(posedge i_clk);
    i_rst = 1'b0;
    @(posedge i_clk);
    ri_in_valid = 1'b1;
    ri_in_data = 16'h1234;
    @(posedge i_clk);
    ri_in_valid = 1'b0;
    repeat (4) @(posedge i_clk);
    if (!ro_out_valid || ro_out_data !== 16'h1234) begin
      $display("FAIL: ${name} basic transfer");
      $finish;
    end
    $display("PASS: ${name}");
    $finish;
  end

  initial begin
    $dumpfile("02_sim/${name}/${name}.vcd");
    $dumpvars(0, tb_${name});
  end
endmodule
`;
}

function generateGitignore() {
  return [
    'work/',
    'transcript',
    '*.log',
    '*.jou',
    '*.vcd',
    '*.vcd.lxt',
    '*.wlf',
    '*.vvp',
    '*.dcp',
    '*.rpt',
    'xsim.dir/',
    '.Xil/',
    '__pycache__/',
    '*.pyc',
    '',
  ].join('\n');
}

function generateReadme(projectName) {
  return `# ${projectName}

Canonical HDL project scaffold generated by harness-init.

## Layout

- RTL: \`01_src/00_hdl/<module>/<module>.sv\`
- Testbench: \`02_sim/<module>/tb_<module>.sv\`
- Constraints: \`03_xdc/<name>.xdc\`
- Docs: \`06_doc/\`
- Directory contract: \`var/project-init/directory-contract.json\`
`;
}

function writeFile(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
}

async function main() {
  const args = process.argv.slice(2);
  if (args.includes('--help') || args.includes('-h')) {
    console.log(usage());
    return;
  }

  let projectName = argValue(args, '--project');
  if (!projectName) projectName = await ask('Project name', 'fpga_project');
  if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(projectName)) {
    throw new Error(`invalid project name: ${projectName}`);
  }

  const device = argValue(args, '--device', 'xc7k325tffg900-2');
  const fmax = argValue(args, '--fmax', '200');
  const toolsReport = detectTools();
  const edaTools = toolsReport.tools || [];
  const lintTool = pickLintTool(edaTools);
  const simulator = argValue(args, '--sim', edaTools.find((tool) => tool.name === 'xsim' && tool.available) ? 'xsim' : 'manual');
  const projectDir = path.resolve(argValue(args, '--dir', path.join(process.cwd(), projectName)));
  const topModule = `${projectName}_top`;
  const paths = modulePaths(topModule);

  section('Create canonical project layout');
  ensureProjectDirs(projectDir, { modules: [topModule] });
  ok(projectDir);

  section('Write project files');
  writeFile(path.join(projectDir, 'Makefile'), generateMakefile(projectName, lintTool, simulator, edaTools));
  ok('Makefile');
  writeFile(path.join(projectDir, '.gitignore'), generateGitignore());
  ok('.gitignore');
  writeFile(path.join(projectDir, 'README.md'), generateReadme(projectName));
  ok('README.md');
  writeFile(path.join(projectDir, 'fpga_constraints.yaml'), generateConstraints(fmax, device));
  ok('fpga_constraints.yaml');
  writeFile(path.join(projectDir, `${projectName}.f`), `# ${projectName} source file list\n${paths.rtl.replace(/\\/g, '/')}\n`);
  ok(`${projectName}.f`);
  writeFile(path.join(projectDir, paths.rtl), generateModule(topModule));
  ok(paths.rtl.replace(/\\/g, '/'));
  writeFile(path.join(projectDir, paths.tb), generateTb(topModule));
  ok(paths.tb.replace(/\\/g, '/'));
  writeDirectoryContract(projectDir, { projectName, modules: [topModule] });
  ok('var/project-init/directory-contract.json');

  section('Summary');
  console.log(JSON.stringify({
    status: 'ok',
    projectDir,
    projectName,
    topModule,
    rtl: paths.rtl.replace(/\\/g, '/'),
    tb: paths.tb.replace(/\\/g, '/'),
    toolchain: toolchainLabel(edaTools),
  }, null, 2));
}

main().catch((error) => {
  console.error(`ERROR: ${error.message}`);
  process.exit(1);
});
