# Generated by extract-cbb.cjs; fail-closed certification recipe.
set script_dir [file dirname [file normalize [info script]]]
if {[info exists ::env(CBB_EDA_SCRIPT_DIR)] && $::env(CBB_EDA_SCRIPT_DIR) ne ""} { set script_dir $::env(CBB_EDA_SCRIPT_DIR) }
proc cbb_eda_path {relative} { global script_dir; if {[info exists ::env(CBB_EDA_SCRIPT_DIR)] && $::env(CBB_EDA_SCRIPT_DIR) ne ""} { return [file join $script_dir $relative] }; return [file normalize [file join $script_dir $relative]] }
if {[file exists work]} { vdel -all -lib work }
vlib work
vlog -sv -lint -work work [cbb_eda_path {../rtl/stream_elastic_pipeline.sv}]
vlog -sv -work work [cbb_eda_path {../sva/stream_elastic_pipeline_sva.sv}]
vlog -sv -work work [cbb_eda_path {../tb/tb_stream_elastic_pipeline.sv}]
vsim -c work.tb_stream_elastic_pipeline -do {run -all; quit -code 0}
