#!/bin/bash
# Claude Code status line — Dracula theme
# Generated by webup-statusline skill

# Ensure jq is available (Windows: WinGet/scoop installs may not be on PATH)
if ! command -v jq >/dev/null 2>&1; then
  for _jq_dir in \
    "$HOME/.claude/bin" \
    "/c/Users/$USERNAME/AppData/Local/Microsoft/WinGet/Links" \
    "/c/Users/$USERNAME/AppData/Local/Microsoft/WinGet/Packages/jqlang.jq_Microsoft.Winget.Source_8wekyb3d8bbwe" \
    "$HOME/scoop/shims" \
  ; do
    if [ -d "$_jq_dir" ] && { [ -x "$_jq_dir/jq" ] || [ -x "$_jq_dir/jq.exe" ]; }; then
      export PATH="$PATH:$_jq_dir"
      break
    fi
  done
fi
# Colors
readonly RST='\033[0m'
readonly C_MODEL='\033[38;2;189;147;249m'
readonly C_CTX_OK='\033[38;2;80;250;123m'
readonly C_CTX_WARN='\033[38;2;241;250;140m'
readonly C_CTX_LOW='\033[38;2;255;85;85m'
readonly C_BAR_EMPTY='\033[38;2;68;71;90m'
readonly C_PCT='\033[38;2;248;248;242m'
readonly C_DIR='\033[38;2;139;233;253m'
readonly C_GIT='\033[38;2;255;184;108m'
readonly C_GIT_DIRTY='\033[38;2;241;250;140m'
readonly C_VIM='\033[38;2;241;250;140m'
readonly C_WORKTREE='\033[38;2;255;121;198m'
readonly C_STYLE='\033[38;2;189;147;249m'
readonly C_COST='\033[38;2;255;215;0m'
readonly C_EFFORT_HIGH='\033[1;38;2;255;85;85m'
readonly C_EFFORT_MED='\033[38;2;241;250;140m'
readonly C_EFFORT_LOW='\033[38;2;80;250;123m'
readonly C_EFFORT_OFF='\033[2;38;2;98;114;164m'
readonly C_SEP='\033[38;2;98;114;164m'

readonly SEP=" | "

# Read JSON from stdin
input=$(cat)

model=$(echo "$input" | jq -r '.model.display_name // ""')
remaining=$(echo "$input" | jq -r '.context_window.remaining_percentage // ""')
ctx_used_tokens=$(echo "$input" | jq -r '.context_window.total_input_tokens // empty')
ctx_window_size=$(echo "$input" | jq -r '.context_window.context_window_size // empty')
# Read effort level from settings (local overrides global)
effort=""
for f in "$HOME/.claude/settings.local.json" "$HOME/.claude/.claude/settings.local.json" "$HOME/.claude/settings.json"; do
  if [ -z "$effort" ] && [ -f "$f" ]; then
    effort=$(jq -r '.effortLevel // empty' "$f" 2>/dev/null)
  fi
done
current_dir=$(echo "$input" | jq -r '.workspace.current_dir // ""')
original_repo_dir=$(echo "$input" | jq -r '.worktree.original_repo_dir // empty')
output_style=$(echo "$input" | jq -r '.output_style.name // empty')
cost_usd=$(echo "$input" | jq -r '.cost.total_cost_usd // empty')
worktree_name=$(echo "$input" | jq -r '.worktree.name // empty')
worktree_branch=$(echo "$input" | jq -r '.worktree.branch // empty')

# Git branch (prefer worktree.branch from input, fall back to git CLI)
git_branch="$worktree_branch"
git_dirty=0
if [ -n "$current_dir" ] && git -C "$current_dir" --no-optional-locks rev-parse --git-dir > /dev/null 2>&1; then
  if [ -z "$git_branch" ]; then
    git_branch=$(git -C "$current_dir" --no-optional-locks branch --show-current 2>/dev/null)
  fi
  if [ -n "$git_branch" ]; then
    if ! git -C "$current_dir" --no-optional-locks diff --quiet 2>/dev/null || \
       ! git -C "$current_dir" --no-optional-locks diff --cached --quiet 2>/dev/null; then
      git_dirty=1
    fi
  fi
fi

# Shorten directory (prefer original repo when in a worktree)
short_dir=""
if [ -n "$original_repo_dir" ]; then
  short_dir=$(basename "$original_repo_dir")
elif [ -n "$current_dir" ]; then
  short_dir=$(basename "$current_dir")
fi

# Progress bar (color scales with remaining context)
bar=""
if [ -n "$remaining" ]; then
  used=$((100 - remaining))
  filled=$((used / 5))
  empty=$((20 - filled))
  if [ "$remaining" -lt 20 ]; then
    ctx_color="$C_CTX_LOW"
  elif [ "$remaining" -lt 50 ]; then
    ctx_color="$C_CTX_WARN"
  else
    ctx_color="$C_CTX_OK"
  fi
  bar="${C_SEP}[${RST}"
  for ((i=0; i<filled; i++)); do bar+="${ctx_color}■${RST}"; done
  for ((i=0; i<empty; i++)); do bar+="${C_BAR_EMPTY}□${RST}"; done
  bar+="${C_SEP}]${RST} ${ctx_color}${used}%${RST}"
  # Append token counts when available: used_tokens/window_size
  if [ -n "$ctx_used_tokens" ] && [ -n "$ctx_window_size" ]; then
    ctx_used_k=$(awk -v v="$ctx_used_tokens" 'BEGIN { printf "%.0fk", v/1000 }')
    ctx_total_k=$(awk -v v="$ctx_window_size" 'BEGIN { printf "%.0fk", v/1000 }')
    bar+="${C_SEP} (${RST}${ctx_color}${ctx_used_k}${RST}${C_SEP}/${RST}${ctx_color}${ctx_total_k}${RST}${C_SEP})${RST}"
  fi
fi

# Assemble
parts=()

if [ -n "$model" ]; then
  parts+=("${C_MODEL}◈ ${model}${RST}")
fi

if [ -n "$bar" ]; then
  parts+=("${bar}")
fi

if [ -n "$cost_usd" ]; then
  cost_formatted=$(awk -v v="$cost_usd" 'BEGIN { if (v+0 >= 0.005) printf "$%.2f", v+0 }')
  if [ -n "$cost_formatted" ]; then
    parts+=("${C_COST}${cost_formatted}${RST}")
  fi
fi

# Color effort by level (max/xhigh/high share the bold-red pressure tier)
if [ -n "$effort" ]; then
  case "$effort" in
    max|MAX|Max|xhigh|XHIGH|XHigh|high|High|HIGH)  effort_color="$C_EFFORT_HIGH" ;;
    medium|Medium|MEDIUM)                          effort_color="$C_EFFORT_MED" ;;
    low|Low|LOW|xlow|XLow|XLOW|minimal|Minimal)    effort_color="$C_EFFORT_LOW" ;;
    *)                                             effort_color="$C_EFFORT_OFF" ;;
  esac
  parts+=("${effort_color}↯ ${effort}${RST}")
fi

if [ -n "$output_style" ] && [ "$output_style" != "default" ]; then
  parts+=("${C_STYLE}❋ ${output_style}${RST}")
fi

if [ -n "$short_dir" ]; then
  parts+=("${C_DIR}⌂ ${short_dir}${RST}")
fi

if [ -n "$git_branch" ]; then
  if [ "$git_dirty" -eq 1 ]; then
    parts+=("${C_GIT_DIRTY}⎇ ${git_branch}${RST}")
  else
    parts+=("${C_GIT}⎇ ${git_branch}${RST}")
  fi
fi

# Output
output=""
for i in "${!parts[@]}"; do
  if [ "$i" -gt 0 ]; then
    output+="${C_SEP}${SEP}${RST}"
  fi
  output+="${parts[$i]}"
done

printf "%b" "$output"
